-- Migration 0001: initial schema.
--
-- Applied with the owner DSN (POSTGRES_USER, superuser in the Postgres image)
-- via MIGRATION_DATABASE_URL. The application runtime never uses this role:
-- see db/init/01-app-role.sh for the creation of the restricted undelete_app
-- role.

-- users: one row per connected Telegram Business account holder.
-- Root of the tenant relationship -> no RLS here: the table is queried
-- directly (upsert by telegram_user_id) before an "owner" context even has
-- any meaning.
CREATE TABLE users (
    id               BIGSERIAL PRIMARY KEY,
    telegram_user_id BIGINT NOT NULL UNIQUE,
    retention_days   INT NOT NULL DEFAULT 7 CHECK (retention_days BETWEEN 1 AND 365),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- business_connections: one row per Telegram Business connection.
-- id = business_connection_id provided by Telegram (opaque text, not an
-- integer generated by us).
--
-- No RLS on this table: it is the RESOLUTION table, queried by connection id
-- *before* knowing who the owner is (business/service.go must first read this
-- table to obtain owner_user_id, before it can set
-- app.current_owner_user_id). An RLS policy here would create a circular
-- dependency: you would need to know the owner to read the row that yields
-- the owner. The small size of this table (one row per Business connection,
-- never user content) makes this risk acceptable.
CREATE TABLE business_connections (
    id             TEXT PRIMARY KEY,
    owner_user_id  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    can_reply      BOOLEAN NOT NULL,
    is_enabled     BOOLEAN NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_business_connections_owner ON business_connections (owner_user_id);

-- messages: the core of the product. One row per message, saved on receipt
-- (business_message / edited_business_message) because the deletion event
-- (deleted_business_messages) does NOT carry the content.
--
-- A message's identity is the quadruple (owner_user_id,
-- business_connection_id, chat_id, message_id): message_id is unique only
-- within a given chat, never globally. Using it alone would cause collisions
-- across different conversations.
CREATE TABLE messages (
    id                      BIGSERIAL PRIMARY KEY,
    owner_user_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    business_connection_id  TEXT NOT NULL,
    chat_id                 BIGINT NOT NULL,
    message_id              BIGINT NOT NULL,
    from_user_id            BIGINT NULL,
    from_display            TEXT NULL,
    message_type            TEXT NOT NULL,
    -- TODO Phase 4: replace text_content (plaintext TEXT) with
    -- text_encrypted BYTEA, encrypted with AES-256-GCM using a per-tenant
    -- key, via a dedicated migration. Phase 1 intentionally stays in
    -- plaintext (content stored in the clear, cf. task scope).
    text_content            TEXT NULL,
    telegram_date           BIGINT NOT NULL,
    saved_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    edited_at               TIMESTAMPTZ NULL,
    deleted_at              TIMESTAMPTZ NULL,
    UNIQUE (owner_user_id, business_connection_id, chat_id, message_id)
);

-- Lookup index on the full quadruple (except owner_user_id, already covered
-- by the UNIQUE constraint above, used for the ON CONFLICT upsert and to find
-- a message on deletion).
CREATE INDEX idx_messages_lookup
    ON messages (business_connection_id, chat_id, message_id);

-- Index for retention purge: scan by owner then by save date.
CREATE INDEX idx_messages_owner_saved_at ON messages (owner_user_id, saved_at);

-- RLS on messages, with FORCE: ENABLE ROW LEVEL SECURITY alone is NOT
-- sufficient. The table owner normally bypasses RLS; FORCE makes the policy
-- applicable to that owner when it is not a superuser and lacks BYPASSRLS.
-- Superusers and BYPASSRLS roles ALWAYS bypass RLS, even with FORCE: the
-- runtime therefore explicitly checks at startup that it is connected as
-- undelete_app, without those attributes (storage.NewPool). The migration
-- superuser role remains strictly reserved for boot.
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages FORCE ROW LEVEL SECURITY;

-- current_setting(..., true) with the second argument true = "missing_ok":
-- if app.current_owner_user_id was never set in the transaction,
-- current_setting returns NULL instead of raising an error. NULLIF(..., '')
-- handles the case where the variable exists but is empty. owner_user_id =
-- NULL never matches any row (NULL is equal to nothing, not even NULL): the
-- behavior is therefore fail-closed by construction. Without this ", true",
-- a query without a context would raise an error instead of silently
-- returning zero rows -- which would be almost acceptable here, but ", true"
-- is what lets us distinguish "context not set" (intended behavior: zero
-- rows) from a genuine application error.
CREATE POLICY tenant_isolation ON messages
    USING (owner_user_id = NULLIF(current_setting('app.current_owner_user_id', true), '')::bigint)
    WITH CHECK (owner_user_id = NULLIF(current_setting('app.current_owner_user_id', true), '')::bigint);

-- TODO Phase 2: media_files table (chat_id, message_id, Telegram file_id,
-- local path under ./media, mime_type) linked to messages by the quadruple;
-- retention/purge to be extended to delete the corresponding files on disk,
-- not just the rows.

-- TODO Phase 2+: GDPR commands (/delete_my_data, /privacy) -> full deletion
-- functions by owner_user_id, to be documented in the README (privacy
-- section) in relation to BACKUP_RETENTION_DAYS.
