#!/bin/sh
# Shared disposable-PostgreSQL bootstrap for integration workloads.
#
# This file is SOURCED, never executed: it defines start_disposable_postgres
# for scripts/test-integration.sh and scripts/test-coverage.sh so the
# container setup lives in exactly one place.
#
# The caller must set ROOT to the repository root before sourcing.
# start_disposable_postgres boots an official postgres:16-alpine container
# (random loopback port, no volume, restricted undelete_app role from
# db/init, removed on EXIT) and exports:
#   POSTGRES_INTEGRATION_ADMIN_DSN / POSTGRES_INTEGRATION_RUNTIME_DSN /
#   POSTGRES_INTEGRATION_ALLOW_DESTRUCTIVE
# Existing containers, networks, images and volumes are never touched.
# Requires docker (checked on entry).

start_disposable_postgres() {
    purpose=${1:-integration}

    if ! command -v docker >/dev/null 2>&1 || ! docker info >/dev/null 2>&1; then
        echo "PostgreSQL integration workloads need a reachable Docker daemon" >&2
        return 1
    fi

    pg_suffix="$$-$(date +%s)"
    pg_container="undelete-pg-$purpose-$pg_suffix"
    pg_admin_password="integration-admin-only"
    pg_runtime_password="integration-runtime-only"

    cleanup_disposable_postgres() {
        # shellcheck disable=SC2154
        docker rm -f "$pg_container" >/dev/null 2>&1 || true
    }
    trap cleanup_disposable_postgres EXIT HUP INT TERM

    docker run --detach --rm \
        --name "$pg_container" \
        --publish 127.0.0.1::5432 \
        --env POSTGRES_USER=postgres \
        --env POSTGRES_PASSWORD="$pg_admin_password" \
        --env POSTGRES_DB=undelete_integration \
        --env APP_DB_USER=undelete_app \
        --env APP_DB_PASSWORD="$pg_runtime_password" \
        --volume "$ROOT/db/init:/docker-entrypoint-initdb.d:ro" \
        postgres:16-alpine >/dev/null

    # Both conditions target 127.0.0.1 and not the Unix socket: during
    # docker-entrypoint-initdb.d, the official image starts a temporary server
    # reachable only by socket. A pg_isready on the socket would therefore succeed
    # BEFORE the init scripts finish and before TCP listening, and the published
    # port would then intermittently refuse connections. The query on pg_roles
    # additionally confirms that db/init/01-app-role.sh ran to completion.
    # PGPASSWORD is essential: the pg_hba.conf generated by the image enforces
    # scram-sha-256 for host connections, including from inside the container.
    pg_attempt=0
    until docker exec "$pg_container" pg_isready -h 127.0.0.1 -U postgres -d undelete_integration >/dev/null 2>&1 &&
        docker exec --env PGPASSWORD="$pg_admin_password" "$pg_container" \
            psql -h 127.0.0.1 -U postgres -d undelete_integration -tAc \
            "SELECT 1 FROM pg_roles WHERE rolname = 'undelete_app'" 2>/dev/null | grep -qx 1; do
        pg_attempt=$((pg_attempt + 1))
        if [ "$pg_attempt" -ge 60 ]; then
            docker logs "$pg_container" >&2 || true
            echo "PostgreSQL 16 or the undelete_app role did not become ready" >&2
            return 1
        fi
        sleep 1
    done

    pg_port=$(docker port "$pg_container" 5432/tcp | awk -F: 'NR == 1 { print $NF }')
    POSTGRES_INTEGRATION_ADMIN_DSN="postgres://postgres:${pg_admin_password}@127.0.0.1:$pg_port/undelete_integration?sslmode=disable"
    POSTGRES_INTEGRATION_RUNTIME_DSN="postgres://undelete_app:${pg_runtime_password}@127.0.0.1:$pg_port/undelete_integration?sslmode=disable"
    POSTGRES_INTEGRATION_ALLOW_DESTRUCTIVE=I_UNDERSTAND_THIS_WILL_DELETE_DATA
    export POSTGRES_INTEGRATION_ADMIN_DSN POSTGRES_INTEGRATION_RUNTIME_DSN POSTGRES_INTEGRATION_ALLOW_DESTRUCTIVE
}
